#!/bin/bash
# instance secorndary AWS connection

echo
ec2-detach-network-interface 
echo "Command to detach Interface $INTERFACE submitted"
while [ "$INTERFACESTATUS" = 'in-use' ]
do
 echo "Will sleep 1 second"
 sleep 1
 INTERFACESTATUS=`ec2-describe-network-interfaces $INTERFACE | \
 awk -F"\t" /NETWORKINTERFACE/'{print $10 }'`
Done
echo "Will attach interface $INTERFACE to $TONODE "
ec2-attach-network-interface $INTERFACE -i
