#!/bin/bash
# instance secorndary AWS conne

 INTERFACESTATUS=`ec2-describe-network-interfaces
 awk -F"\t" /NETWORKINTERFACE/'{print $10 }'`
Done
echo "Will attach interface $INTERFACE to $TONODE "
ec2-attach-network-interface $INTERFACE -i
